# Generated by Django 4.0.6 on 2022-07-31 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jew_data', models.TextField(unique=True)),
                ('chumash', models.TextField()),
                ('tehillim', models.TextField()),
                ('tanya', models.TextField()),
                ('hayom_yoma', models.TextField()),
                ('rambam', models.TextField()),
                ('moshiach', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
