version: '3'

services:
  kolel_bot:
    build: 
      context: /bot
      dockerfile: Dockerfile 
    restart: always

  backend:
    build:
      context: ./webapp/backend
      dockerfile: Dockerfile
    restart: always
    expose:
      - 8000
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000 --noreload"
  
  frontend:
    build:
      context: ./webapp/frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    command: >
      sh -c "npm run build &&
             npm install -g serve &&
             serve -s build"

networks:
  default:
    external:
      name: nginx-networks